repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: no-commit-to-branch
        args:
          - --branch
          - main
      - id: trailing-whitespace

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: \.sh$

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-2
    hooks:
      - id: shfmt
        files: \.sh$
        args:
          - -w
          - -i
          - "2"
          - -ci
