name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake syntax and inputs
        run: nix flake check

      - name: Build Home Manager configuration
        run: nix build .#homeConfigurations.ryosh.activationPackage

      - name: Run shellcheck
        run: shellcheck scripts/*.sh scripts/units/*.sh
